# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_folder(path = "/Users/carsonhalls/Documents/GitHub/is-555-00-in-class-activities-w24")
v <- vetiver_pin_read(b, "house_prices")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
